### ISSUE TITLE
Null Error

### ISSUE THREAD

**Issue by Sprungente** [NLthijs48/AreaShop#429] opened 2018-09-27 13:27 UTC
**Current behavior**
I found it in the console. What exactly will happen i don't but it looks that the Regionupdate Event are involved.

https://hastebin.com/ijohanorim.cs

**Steps to reproduce**
I don't know when the issues was here and i don't know how to reproduce

**Your environment**
* Server platform: Spigot
* Server version: 1.13.1 This server is running CraftBukkit version git-Spigot-68acb93-7d506c6 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
* AreaShop version: Build 249
* WorldEdit version: FastAsyncWorldEdit Build 2050
* WorldGuard version: WorldGuard 7.0.0-SNAPSHOT;7fb7d59
* Vault version: 1.7.1

**Comment by NLthijs48** [comment] 2018-10-20 15:54
It looks like you only copied a part of the logging in the console, the part that I need to find the problem is missing. Could you send me your complete log file? I heard from other people that the WorldEdit build of FastsAsyncWorldEdit does not work with AreaShop, so maybe that is the issue.

**Comment by Sprungente** [comment] 2018-10-20 15:57
that soo long ago :/  
FAWE don't work well at the moment. Very broken on 1.13.1. Since i remove Fawe it is working  

Hope another one has the same issue and send the log

**Comment by NLthijs48** [comment] 2018-10-22 21:21
I'm tracking FAWE support in this issue https://github.com/NLthijs48/AreaShop/issues/436, I'll close this issue as duplicate.

**Closed by NLthijs48** 2018-10-22 21:21 UTC
Labels: Type: Bug
