### ISSUE TITLE
RegionUpdateEvent Error

### ISSUE THREAD

**Issue by Nightfighter001** [NLthijs48/AreaShop#178] opened 2016-06-27 16:09 UTC
Hi,
I tried to start my Server with AreaShop v. "2.2.2" and WorldGuard v. "worldguard-legacy-6.1.3-SNAPSHOT-dist". The Spigot Version is "git-Spigot-5391d73-00359a1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)".
I got this Error:
`Could not pass event RegionUpdateEvent to AreaShop v2.2.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5391d73-00359a1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5391d73-00359a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5391d73-00359a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5391d73-00359a1]
        at nl.evolutioncoding.areashop.regions.GeneralRegion.update(GeneralRegion.java:185) [AreaShop.jar:?]
        at nl.evolutioncoding.areashop.managers.FileManager$3.run(FileManager.java:487) [AreaShop.jar:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-5391d73-00359a1]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5391d73-00359a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot.jar:git-Spigot-5391d73-00359a1]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-5391d73-00359a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-5391d73-00359a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-5391d73-00359a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at nl.evolutioncoding.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:93) ~[?:?]
        at nl.evolutioncoding.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:26) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-5391d73-00359a1]
        ... 12 more
`
I think you have to recompile AreaShop with the newest Version of WorldGuard.

Thank you :)

**Comment by NLthijs48** [comment] 2016-06-27 21:27
Update AreaShop to the [latest development build](http://wiefferink.me:8080/job/AreaShop/) or downgrade WorldGuard to the latest stable version (which is already compatible with 1.10). I will soon (this weekend hopefully) release an update of AreaShop based on the dev builds.

Duplicate of #170

**Closed by NLthijs48** 2016-06-27 21:27 UTC
Labels: Duplicate
