### ISSUE TITLE
saving/restoring schematics error

### ISSUE THREAD

**Issue by titanium63** [NLthijs48/AreaShop#421] opened 2018-09-06 10:56 UTC
Hello,
**Current behavior**
/as add rent working but not the save schematic
/as schemevent don't load schematic 

**Expected behavior**
save and load schematic 

**Steps to reproduce**
1. atcivate schematic profile on rented or bought
2. create a region with worldguard
3. use /as add rent or buy 
4. rented or bought this region and i have this in my console

> [12:05:12] [Server thread/WARN]: [AreaShop] org.bukkit.command.CommandException: Unhandled exception executing command 'areashop' in plugin AreaShop v2.4.0#249
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695)
	at me.wiefferink.areashop.regions.GeneralRegion.runCommands(GeneralRegion.java:1437)
	at me.wiefferink.areashop.features.signs.RegionSign.runSignCommands(RegionSign.java:231)
	at me.wiefferink.areashop.features.signs.SignsFeature.onSignClick(SignsFeature.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238)
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452)
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1240)
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150)
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at me.wiefferink.areashop.handlers.WorldEditHandler7.saveRegionBlocks(WorldEditHandler7.java:152)
	at me.wiefferink.areashop.regions.GeneralRegion.saveRegionBlocks(GeneralRegion.java:752)
	at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1404)
	at me.wiefferink.areashop.regions.RentRegion.rent(RentRegion.java:591)
	at me.wiefferink.areashop.commands.RentCommand.execute(RentCommand.java:42)
	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	... 27 more

1. /as schemevent
In console : 

> org.bukkit.command.CommandException: Unhandled exception executing command 'areashop' in plugin AreaShop v2.4.0#244
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1644) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1479) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/patterns/Pattern
	at com.sk89q.worldedit.EditSessionFactory$EditSessionFactoryImpl.getEditSession(EditSessionFactory.java:155) ~[?:?]
	at me.wiefferink.areashop.handlers.WorldEditHandler7.saveRegionBlocks(WorldEditHandler7.java:146) ~[?:?]
	at me.wiefferink.areashop.regions.GeneralRegion.saveRegionBlocks(GeneralRegion.java:752) ~[?:?]
	at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1408) ~[?:?]
	at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:711) ~[?:?]
	at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:79) ~[?:?]
	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	... 15 more

 

**Your environment**
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.13.1
* AreaShop version: devbuild #249
* WorldEdit version: 7.0.0
* WorldGuard version: 7.0.0
* Vault version: 1.6.6

**Comment by EscolarProgramming** [comment] 2018-09-07 17:43
Same here:
`[19:32:48 INFO]: Escolar issued server command: /as schemevent h1e4l-001 unrented
[19:32:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1740) ~[?:?]
        at me.wiefferink.areashop.commands.SchematiceventCommand.execute(SchematiceventCommand.java:67) ~[?:?]
        at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:112) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2_15.12.jar:git-Spigot-549c1fa-2ee49b4]
        ... 15 more
`

- Server platform: SpiGot
- Server version: 1.12.2
- AreaShop Verion: 2.4.0 (latest on SpiGot)
- WorldEdit version: 6.1.9
- WorldGuard version: 6.2.2
- Vault version: 1.5.6

**Comment by Sprungente** [comment] 2018-09-16 01:56
additional information:
New Areas won't save schematics. Also sign don't work fine anymore. Maybe because the Schmaticbug areas aren't sellable

https://pastebin.com/F6WhHmwL

**Comment by NLthijs48** [comment] 2018-10-20 13:05
Does the latest developer build fix this issue?
http://wiefferink.me:8080/job/AreaShop/

**Comment by Sprungente** [comment] 2018-10-20 13:33
with vanillaworldedit and worldguard it is working

**Comment by EscolarProgramming** [comment] 2018-10-20 19:15
Actually the command works fine (there's no error in console) but nothing happen ^^
The schems won't be saved (as well with command as by default).
Updated platform list:
- SpiGot 1.13.1
- AreaShop Build #255 
- WorldEdit 7.0.0
- WorldGuard 7.0.0
- Vault 1.7.1

**Comment by NLthijs48** [comment] 2018-10-20 22:15
@EscolarProgramming Try enabling the `debug` setting in the `config.yml` file of AreaShop, then repeat your test. The log file/console should indicate why AreaShop is not saving and/or restoring the schematic files.

If that does not indicate enough, please send me your config files so that I can check why it does not work.

**Comment by NLthijs48** [comment] 2018-10-21 20:12
I made a change in AreaShop that might make it work with FAWE, you can test it using the latest developer build.

To keep together all info about FAWE support I will close this issue as duplicate and continue the conversation in https://github.com/NLthijs48/AreaShop/issues/436, to keep all info in one place.

**Closed by NLthijs48** 2018-10-21 20:12 UTC
Labels: Type: Bug
