### ISSUE TITLE
Just can'tget the regions to work lol

### ISSUE THREAD

**Issue by cloakfox** [NLthijs48/AreaShop#210] opened 2016-08-13 14:11 UTC
Indicate the steps you did while encountering the problem, the expected outcome, and the actual outcome. Provide links to your config.yml, default.yml and groups.yml files (use pastebin.com or similar). Also provide a full startup log of your server (this indicates the plugin versions used).

So yeah I am trying to setup a bunch of cells, but no one can build in them. I have been messing with it for a straight 3 hours and nothing works.

Once I managed to fix it, everyone could place/break blocks in the cells.
Only thing that worked with the non_members thing was chest-access and entry flags. Those properly worked. The rest did not..

Flags: http://imgur.com/a/U1ykN

I hope you could help me out,

Adding me on skype will also speed up that process most likely.
Skype: cloakfox (from the netherlands)

**Comment by cloakfox** [comment] 2016-08-15 11:57
These are the flags of the underlying region: http://imgur.com/a/6Hjrb

**Comment by NLthijs48** [comment] 2016-08-19 18:24
Removing the `block-break`, `block-place` and `build` flags, those are not required (a region can only edited by its members/owners by default).

I'm available this evening so if this does not solve it comment here and we could meet on Skype/TeamSpeak

**Comment by cloakfox** [comment] 2016-08-19 18:31
Just tried that, didn't work. The it has a higher priority then the region below it so to say.

Skype: cloakfox (from the netherlands)

**Comment by NLthijs48** [comment] 2016-08-19 19:49
Fixed on Skype, was caused by `block-break` and `block-place` on DENY on a lower priority region.

**Closed by NLthijs48** 2016-08-19 19:49 UTC
Labels: Support
