### ISSUE TITLE
 String index out of range: -1

### ISSUE THREAD

**Issue by TNTUP** [NLthijs48/AreaShop#208] opened 2016-08-09 19:42 UTC
#### Current behavior

Getting errors at startup (See spigot's thread)

[15:37:15] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.3.2#CUSTOM
[15:37:15] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.3.2#CUSTOM (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_91]
	at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:166) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:409) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:374) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:328) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:575) [patched_1.10.2.jar:git-Paper-820]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[15:37:15] [Server thread/INFO]: [AreaShop] Disabling AreaShop v2.3.2#CUSTOM
[15:37:15] [Server thread/ERROR]: Error occurred while disabling AreaShop v2.3.2#CUSTOM (Is it up to date?)
java.lang.NullPointerException
	at me.wiefferink.areashop.AreaShop.onDisable(AreaShop.java:339) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:323) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:409) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:374) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:328) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:575) [patched_1.10.2.jar:git-Paper-820]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

#### New behavior

Should launch without errors (Got the fix you did and I got an ew error)
#### Steps to reproduce (for bugs)

1. Start the server and you'll see it will enable/disable due a Index out of bounds -1 :/
2. 
3. 
4. 

#### Your environment

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 1.10.2 (Paper) (See my last issue, too lazy to retype them again)
* AreaShop version: 
* WorldEdit version: 
* WorldGuard version: 
* Vault version:

**Comment by NLthijs48** [comment] 2016-08-09 19:58
Should be fixed by b3408a2648260f9bfd94da55032c6eb9ec6344dd, could you confirm that by downloading it from [here](http://wiefferink.me:8080/job/AreaShop/)?

I guess that you changed your WorldGuard version, and that is what AreaShop breaks on. Thank you for reporting the problem.

**Comment by TNTUP** [comment] 2016-08-09 20:28
Downloaded it and I got it while loading with plugman: [16:26:08] [Server thread/WARN]: [AreaShop] Could not correctly parse the build of WorldGuard, raw version: 6.1.3-SNAPSHOT;e5e1f71, buildNumber: e5e1f71 and indeed I've cloned their repo and I removed the hopper check code, shouldn't cause issues with AS. 

Also those errors were spamming the console heavily (I've only included 3 stack traces)

[16:26:27] [Server thread/ERROR]: Could not pass event RegionUpdateEvent to AreaShop v2.3.2#68
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
	at me.wiefferink.areashop.handlers.WorldGuardHandler6.fuzzyMatchFlag(WorldGuardHandler6.java:116) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:109) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:45) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1111.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-820]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-820]
	at me.wiefferink.areashop.regions.GeneralRegion.update(GeneralRegion.java:214) [AreaShop.jar:?]
	at me.wiefferink.areashop.managers.FileManager$3.run(FileManager.java:476) [AreaShop.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-820]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[16:26:27] [Server thread/ERROR]: Could not pass event RegionUpdateEvent to AreaShop v2.3.2#68
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
	at me.wiefferink.areashop.handlers.WorldGuardHandler6.fuzzyMatchFlag(WorldGuardHandler6.java:116) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:109) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:45) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1111.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-820]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-820]
	at me.wiefferink.areashop.regions.GeneralRegion.update(GeneralRegion.java:214) [AreaShop.jar:?]
	at me.wiefferink.areashop.managers.FileManager$3.run(FileManager.java:476) [AreaShop.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-820]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[16:26:27] [Server thread/ERROR]: Could not pass event RegionUpdateEvent to AreaShop v2.3.2#68
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
	at me.wiefferink.areashop.handlers.WorldGuardHandler6.fuzzyMatchFlag(WorldGuardHandler6.java:116) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:109) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:45) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1111.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-820]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-820]
	at me.wiefferink.areashop.regions.GeneralRegion.update(GeneralRegion.java:214) [AreaShop.jar:?]
	at me.wiefferink.areashop.managers.FileManager$3.run(FileManager.java:476) [AreaShop.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.10.2.jar:git-Paper-820]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-820]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-820]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by NLthijs48** [comment] 2016-08-09 20:39
Somewhere in WorldGuard 6.1.3 the region flag system changed, which means I need to load a different implementation to set the flags for the AreaShop regions. The problem is that it changed at a specific build number, which I try to get from the version string. Normally that works fine, but your version does not contain a build number because you compiled it yourself. Even then AreaShop simply falls back to the newest implementation now, but apparently you have a slightly outdated build, which is from before the flag changes. So I recommend updating your WorldGuard build or using an official release of them, and then the issue is solved.

**Comment by TNTUP** [comment] 2016-08-09 20:44
This shouldn't be 6.1.3 because I've cloned their repo at (https://github.com/sk89q/WorldGuard/) so well their 6.1.4 must be somewhere and recompile it... I'll try finding it and if its my WG issue I'll close this issue (related to WG not AS)

**Comment by NLthijs48** [comment] 2016-08-09 20:46
There is no 6.1.4 yet, the version number in their repo is still 6.1.3, I think the only thing you need to do is `git remote update` and `git rebase origin/master` (assuming you committed your changes). Then you apply your changes to the latest version of WorldGuard, your repository is probably a few commits behind (when did you clone it?).

**Comment by TNTUP** [comment] 2016-08-09 20:47
I did clone it yesterday. The only commit I need to redo is removing the hopper check code and then recompile

**Comment by NLthijs48** [comment] 2016-08-09 20:57
In your case the WorldGuard version would fallback to 6 instead of 6.1.3+, so that is indeed wrong, I changed the detection to have better defaults, try the [latest build of AreaShop](http://wiefferink.me:8080/job/AreaShop/) and see if that works.

**Comment by TNTUP** [comment] 2016-08-09 21:01
I tried it on my Windows VPS and it worked, but now I'll go give a try on my production server

**Closed** 2016-08-09 21:01 UTC
Labels: Bug
