### ISSUE TITLE
error at bootup with worldedit

### ISSUE THREAD

**Issue by Ironic8b498** [NLthijs48/AreaShop#460] opened 2018-12-06 04:50 UTC
**Current behavior**

**Expected behavior**

**Steps to reproduce**

1. 
2. 
3. 
4. 

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 
* WorldEdit version: 
* WorldGuard version: 
* Vault version: 

**Your config files**

**Comment by Ironic8b498** [comment] 2018-12-06 04:55
Current behavior
seems to work, has error when creating a sign about region
Expected behavior
no errors messages
Steps to reproduce
boot server with
worldedit-bukkit-7.0.0-SNAPSHOT-dist-#3948
AreaShop-2.5.0
Your environment
MC 1.13.2
Server platform (Bukkit, Spigot, etc.): Spigot/bukkit
Server version:
AreaShop version: 2.5.0
WorldEdit version: 7.0.0-SNAPSHOT-dist-#3948
WorldGuard version: 7.0.0-SNAPSHOT-dist-1758
Vault version: 1.7.1
Your config files

error message
https://hastebin.com/fobesuroya.cs

**Comment by Pyario** [comment] 2018-12-06 15:36
Yes with new Version of Worldguard/WorldEdit has AreaShop (newest Version) Problems with start. Please fix them

**Comment by motherboard1999** [comment] 2018-12-09 15:30
Yeah I have same the same problem:
`[16:23:58 INFO]: [AreaShop] Enabling AreaShop v2.5.0
[16:23:58 ERROR]: Error occurred while enabling AreaShop v2.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_191]
        at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:251) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]`

If I try to use a command:
`[16:27:02 INFO]: Motherboard1999 issued server command: /as rent
>
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 14 more`

**Comment by NLthijs48** [comment] 2018-12-27 21:35
This is the same problem as described in [this issue](https://github.com/NLthijs48/AreaShop/issues/452), install the latest development build to fix it.

I'll close this issue as duplicate.

**Closed by NLthijs48** 2018-12-27 21:35 UTC
