### ISSUE TITLE
Sign disappearing after unrent, as reload fixes that.

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#65] opened 2015-09-01 07:38 UTC
As the topic says since the daily restart this morning I have a weird issue that lets as signs disappear after unrenting a region.
A `/as reload` fixes this and the signs re-appearing. Debug mode is enabled and I waited if a periodic sign update fixes it but it doesn't.
Unfortunately AreaShop does not provide any further debug information.

`config.yml` http://pastebin.com/88KMAHXj
`default.yml` http://pastebin.com/Q8cKA3zX
These pastes will expire in one month from now.

The only thing I changed till then was adding `chest-access` to the flags section. I removed this again for testing purpose but did not change the behavior.

v2.2.0

**Comment by NLthijs48** [comment] 2015-09-04 19:08
Signs will only disappear if all the lines `line[1-4]` are empty in the signProfile of the sign. So it might be that the assigned signProfile is missing/broken, therefore removing the signs. Check the `<region>.yml` file to see if the sign with trouble has a signprofile, then check for a general signprofile in the `<region.yml>`, then for groups assigned to the region, and lastly the default file.

The periodic sign update task will not do anything about this problem, that will only update signs that have the `%timeleft%` tag on them (only time-sensitive tag). So you don't have to check on that.

Since you are describing that `/as reload` fixes the problem I don't really get where the problem is coming from. If you can describe a way to reproduce this problem then I might try it myself with your config, maybe I can spot the problem then.

**Comment by EvilOlaf** [comment] 2015-09-04 20:03
SignProfiles are correct. Otherwise they won't work (again) on (re)load.
I checked all `region` files and the only difference between is that one contains `lastActive:` and `Duration:` line. This particular one I used for testing. I set the duration from default 7 days to 2 days (german `Tage` which is added to the bunch of terms at the `config.yml`). That part works well.

```
$:~/plugins/AreaShop/regions$ cat shop1.yml
general:
  name: shop1
  world: Survival
  type: rent
  signs:
    '0':
      location:
        world: Survival
        x: 3150.0
        y: 74.0
        z: 1535.0
      facing: SOUTH
      signType: WALL_SIGN
  lastActive: 1441290747155
rent:
  price: 1606.0
  duration: 2 Tage
```


```
$:~/plugins/AreaShop/regions$ cat shop2.yml
general:
  name: shop2
  world: Survival
  type: rent
  signs:
    '1':
      location:
        world: Survival
        x: 3159.0
        y: 74.0
        z: 1534.0
      facing: WEST
      signType: WALL_SIGN
rent:
  price: 2486.0
```
All other regions look like `shop2` as they have not been used yet.

**Comment by EvilOlaf** [comment] 2015-09-10 15:23
After a bit of testing I could isolate the issue to sigs that are within an area that  will schematic restore after unrent (no surprise), but also within a range of 1 block AROUND the rented region. If I move the sign to a place two block or more away from the restored area it does not disappear.

**Comment by NLthijs48** [comment] 2015-09-11 21:00
The situation that signs get removed by the restore action seems plausible. At unrent I actually perform the schematicEvent first (which will restore the region if that is specified in the config), and after that update the signs ([see the source](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/java/nl/evolutioncoding/areashop/regions/RentRegion.java#L603-L613)). Are you correctly using the schematic profiles to restore the region? Are you maybe using the eventCommandProfiles section to restore the region by performing a command? Do you have a plugin that changes the functions of WorldEdit in any way (maybe the restore is happening late somehow)?

I just see that you mention you have polygon regions, those will indeed cause trouble. AreaShop will save/restore them like a cuboid, so it will save/restore too much blocks. I already have an issue for this bug on the tracker: #20. So if the part that is restored as extra is inside another region, at the place where a sign is located, then that part is overwritten and causes the problem that you describe.

Let me know if the polygon restoring problem might be the causing the effects you see.

**Comment by EvilOlaf** [comment] 2015-09-12 05:46
Meanwhile I am pretty sure that the poly region and wrongly saved schematics causing the issues both the signs disappearing as well as "too many blocks" being restored.

As for your question about the schematic  saving feel free to take a look at my config files above. I did not change anything there since report creating.

Besides WorldEdit there is AsyncWorldEdit running, but no idea if this plugin will stick between if a plugin like AreaShop using the WE API instead of running common WorldEdit commands ingame.

Best regards
Olaf

**Comment by NLthijs48** [comment] 2015-09-12 12:54
If the poly regions have a layout that could cause the extra corners to change other regions then I think that is the problem. The too many blocks thing can be fixed by increasing the `maximumBlocks` setting in `config.yml`.

I'm not sure if AsyncWorldEdit is getting used when I invoke the schematic loading/saving with the functions in WorldEdit, might have to test that sometime. In my opinion having the signs inside of the region does not make much sense anyway, since that is only limiting the player for that 1 block space.

The polygon regions problem is something I will be looking at, but I'm not sure if and when it might be resolved, because it might be a very hard thing to fix if there is no WorldEdit functions for doing it.

**Comment by NLthijs48** [comment] 2015-10-03 18:14
I'm closing this issue because the core problem is already described in issue #20, I will keep track of it there.

**Closed by NLthijs48** 2015-10-03 18:14 UTC
Labels: Support

**Comment by EvilOlaf** [comment] 2015-10-03 18:15
Sounds good.
