### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by HollishKid** [NLthijs48/AreaShop#237] opened 2016-10-05 17:11 UTC
Hello,

I'm going to take the liberty not to use your issues template, simply because I have no issue whatsoever with your plugin. It's quite simply outstanding and working as you intended it to ! =)

This is a feature request. Could you make it so that players are automatically teleported to their nearest or only rented/bought region when using the teleportation command without specifying a region name?

This would allow me to integrate it in ChestCommands and give it a nice touch of simplicity !

Thanks for considering man !
Keep it up =D

**Comment by NLthijs48** [comment] 2016-10-11 19:17
There is already an issue open to improve the `/as tp` command and possibly add the `/as home` command to teleport to the region of the a player when they only have one. The details still need to be worked out though.

#39

So I'll close this issue as duplicate of that one and keep tracking it there, thank you for your input though, for sure it shows this feature should still be added.

**Closed by NLthijs48** 2016-10-11 19:17 UTC
