### ISSUE TITLE
Reset LWC Protections

### ISSUE THREAD

**Issue by timafh** [NLthijs48/AreaShop#14] opened 2015-05-04 18:05 UTC
Hi,

can you add resetting LWC protections within AreaShop-Regions, for example when a rent timeframe is over and the region gets resettet and freed for re-rent?

**Comment by NLthijs48** [comment] 2015-05-09 20:24
Adding support for that is on my TODO list, but might take a while. I will have to make some changes to support this nicely, possibly doing this together with adding an API.

I think I will leave this ticket here and report progress when I start implementing it.

**Comment by timafh** [comment] 2015-05-11 11:28
Nice, thank you!

**Comment by NLthijs48** [comment] 2015-10-06 18:58
Closing this as duplicate of #19, did not check properly if an issue for it did exits.

**Closed by NLthijs48** 2015-10-06 18:58 UTC
Labels: Feature
