### ISSUE TITLE
Duplicating items

### ISSUE THREAD

**Issue by ChronoShaman** [NLthijs48/AreaShop#340] opened 2017-07-24 02:02 UTC
#### Current behavior

Items that are dropped into the rentable regions can be duplicated.  Players can drop a sword, rent the region, unrent the region and the sword will duplicate on the ground.

#### Steps to reproduce (for bugs)

1. Drop item in rentable region.
2. Rent region.
3. Unrent region.
4. Item is duplicated.

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 1.12 Spigot
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.7.2
* WorldGuard version: 6.2.2
* Vault version: 1.6.1

**Comment by EvilOlaf** [comment] 2017-07-24 05:24
That is more likely a WorldEdit problem?

**Comment by NLthijs48** [comment] 2017-07-24 07:55
Duplicate of #273, I still do not have a good solution for the problem except disabling the schematic save on rental. The solution I would like to have is excluding entities when saving or loading the schematic.

I'll close this one and keep the other one open.

**Closed by NLthijs48** 2017-07-24 07:55 UTC
