### ISSUE TITLE
Vector error... make sure you update it all....

### ISSUE THREAD

**Issue by Jupiterbe** [NLthijs48/AreaShop#467] opened 2018-12-28 23:47 UTC
**Current behavior**
as unrent wil call for the vector of worldedit

**Expected behavior**
to actuly work....

**Steps to reproduce**
1.  Update all plugins
2. rent a shop
3. type /as unrent
4. panic over the exploding console...

**Your environment**
latest paperclip

* Server version: 488
* AreaShop version: 271
* WorldEdit version: 3992 (we 7)
* WorldGuard version: 1779 (we 7)
* Vault version: 1.7.1 (10>>> https://ci.md-5.net/job/Vault/ )

org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.5.0#271
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-488]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at me.wiefferink.areashop.handlers.WorldGuardHandler6.getApplicableRegionsSet(WorldGuardHandler6.java:42) ~[?:?]
        at me.wiefferink.areashop.tools.Utils.getImportantRegions(Utils.java:458) ~[?:?]
        at me.wiefferink.areashop.tools.Utils.getImportantRentRegions(Utils.java:419) ~[?:?]
        at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:54) ~[?:?]
        at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-488]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-488]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at me.wiefferink.areashop.handlers.WorldGuardHandler6.getApplicableRegionsSet(WorldGuardHandler6.java:42) ~[?:?]
        at me.wiefferink.areashop.tools.Utils.getImportantRegions(Utils.java:458) ~[?:?]
        at me.wiefferink.areashop.tools.Utils.getImportantRentRegions(Utils.java:419) ~[?:?]
        at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:54) ~[?:?]
        at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-488]
        ... 15 more

**Comment by CCAdminMC** [comment] 2018-12-29 05:31
I was informed in World Edit IRC that since June the Vector class has been renamed Vector3. The path to Vector3 is now: 

`com\sk89q\worledit\math\Vector3`

There also appears to be a Vector2 class. I am not aware of whether or no this was included in previous releases. If not, then the Vector class may have been broken up into two classes and there may be a bit more refactoring involved to get AS back up and running.

**Comment by CCAdminMC** [comment] 2018-12-29 15:58
So just realized this was a duplicate of https://github.com/NLthijs48/AreaShop/issues/452
Will test the new Dev build and see if this allows the plugin to load and will report any unusual behavior.

**Comment by Rouchesta** [comment] 2019-01-01 17:45
Same problem for me ;-)

**Closed** 2019-01-01 18:30 UTC

**Comment by NLthijs48** [comment] 2019-01-01 18:35
Latest development build fixes this issue!

**Comment by Rouchesta** [comment] 2019-01-01 21:51
Just tested. That's true thank you :-)
