### ISSUE TITLE
interactivemessenger

### ISSUE THREAD

**Issue by Bluqe** [NLthijs48/AreaShop#291] opened 2017-02-21 19:03 UTC
#### Current behavior

Hello, im trying to edit the source code but it says that interactivemessenger is missing and there is no file for it: import me.wiefferink.interactivemessenger.processing.Message;

#### New behavior

I would like a download for this!

#### Steps to reproduce (for bugs)

1.  Just download the source.
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version:  latest
* WorldEdit version:  lastest
* WorldGuard version:  latest
* Vault version:  latest

**Comment by NLthijs48** [comment] 2017-02-21 19:12
To compile AreaShop you can best use Maven, do you have any experience with that?

The source of InteractiveMessenger can be found at https://github.com/NLthijs48/InteractiveMessenger, compiled jar files and jar files with sources can also be downloaded here: http://wiefferink.me:8080/job/InteractiveMessenger/

For compiling using Maven you can check out this page: https://github.com/NLthijs48/AreaShop/wiki/Compiling-AreaShop

**Comment by Bluqe** [comment] 2017-02-22 23:51
How would i do it with eclipse?

**Comment by Bluqe** [comment] 2017-02-23 01:08
Im getting an error with the filemanager with the file.move?? its saying that it doesnt exists or something?

**Comment by NLthijs48** [comment] 2017-02-23 12:22
I did not write a guide for Eclipse yet, I'm not using that myself so I need to install that sometime to write one. I found these instructions that you could follow: [https://www.tutorialspoint.com/maven/maven_eclispe_ide.htm](https://www.tutorialspoint.com/maven/maven_eclispe_ide.htm)

No idea what kind of error you are talking about, you need to show me the complete error by typing it here or showing a screenshot or otherwise I can't help you with that.

What are you trying to edit in the source of AreaShop? Because maybe that can be avoided completely.

**Comment by NLthijs48** [comment] 2017-04-17 19:40
I assume the issue is solved, closing the issue

**Closed by NLthijs48** 2017-04-17 19:40 UTC
Labels: Support
