### ISSUE TITLE
Do.forAll() iteration failed for object: AreaShopPlot

### ISSUE THREAD

**Issue by BoozleDoof** [NLthijs48/AreaShop#474] opened 2019-01-16 01:55 UTC
**Current behavior**
```
[00:02:09] [Server thread/ERROR]: [AreaShop] Do.forAll() iteration failed for object: PS_F1_Shop3+
java.lang.RuntimeException: The operation to load user data for 'b6dec978-6bff-4b93-96db-adce7d83af84' was cancelled by LuckPerms. This is NOT a bug. 
The lookup request was made on the main server thread. It is not safe to execute a request to 
load username data from the database in this context. 
If you are a plugin author, please consider making your request asynchronously. 
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true 
in the LP config, but should consider the consequences (lag) before doing so.
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.lookupUser(VaultPermissionHook.java:136) ~[LuckPerms-Bukkit-4.3.17.jar:?]
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.userHasPermission(VaultPermissionHook.java:162) ~[LuckPerms-Bukkit-4.3.17.jar:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:154) ~[LuckPerms-Bukkit-4.3.17.jar:?]
	at me.wiefferink.areashop.AreaShop.hasPermission(AreaShop.java:615) ~[AreaShop2.6.0.jar:?]
	at me.wiefferink.areashop.regions.RentRegion.rent(RentRegion.java:438) ~[AreaShop2.6.0.jar:?]
	at me.wiefferink.areashop.regions.RentRegion.extend(RentRegion.java:424) ~[AreaShop2.6.0.jar:?]
	at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:351) ~[AreaShop2.6.0.jar:?]
	at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:230) [AreaShop2.6.0.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:888) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [custom.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Expected behavior**
According to the Error, an Asynchronous lookup, haha.

**Steps to reproduce**
No reproduction steps.
I have multiple Buy & Rent plots currently with tenants.
The only plots throwing errors are the Rental Plots.

**Your environment**
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* AreaShop version: 2.6.0
* WorldEdit version: 7.0.0-beta-04;17f52cb
* WorldGuard version: 7.0.0-beta-01;01dfebe
* WorldGuardExtraFlags version: 4.1.1
* Vault version: 1.7.1-b91

**Your config files**
[WorldGuard.zip](https://github.com/NLthijs48/AreaShop/files/2762284/WorldGuard.zip)
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/2762285/AreaShop.zip)

**Comment by BoozleDoof** [comment] 2019-01-21 05:55
Changing the following in default.yml rid the console of the message.

Original Setting (Causing the error)
autoExtend: true

Adjusted Setting (No Error)
autoExtend: false

When autoExtend is set to True;
If the player is online, it extends the rent and draws from the account as it should when rent expires.
If the player is offline, it throws the original error and does nothing to the plot.

**Comment by NLthijs48** [comment] 2019-01-26 18:58
Thank you for the detailed bug report!

This is actually a duplicate of https://github.com/NLthijs48/AreaShop/issues/441. Because the 'autoExtend' feature checks permissions while extending the rental this causes this warning from LuckPerms. You can ignore the warning and enable the suggested setting in the config to get rid of it. I'll see if I can prevent this issue, but I'm not sure yet how to solve it properly (without breaking other permission plugins).

I'll close this issue as duplicate to keep further conversation on the other issue.

**Closed by NLthijs48** 2019-01-26 18:58 UTC
Labels: NEW, Type: Bug
