### ISSUE TITLE
Color codes/bold do not work in shop areas

### ISSUE THREAD

**Issue by 0xC1A551C** [NLthijs48/AreaShop#481] opened 2019-02-18 06:00 UTC
**Current behavior**

![image](https://user-images.githubusercontent.com/36227001/52930912-32181880-32ff-11e9-83a7-7f84935ac8f0.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/36227001/52930927-43f9bb80-32ff-11e9-882a-205ef74619b9.png)

**Steps to reproduce**

1.  Change the chat prefix to `&6&lMarketaplace &7&l»[reset]'`
2.  Walk into a region to see that the &l does nothing for the unicode.
3. 
4.

**Comment by NLthijs48** [comment] 2019-03-02 21:39
Thanks for reporting the issue, it looks like this is a duplicate of https://github.com/NLthijs48/AreaShop/issues/446 though, so I'll close this one and keep the other one.

**Closed by NLthijs48** 2019-03-02 21:39 UTC
Labels: Type: Bug
