### ISSUE TITLE
[bug] Updating groups.yml does not update shops, there is no way to update existing shops

### ISSUE THREAD

**Issue by FrozenBeard** [NLthijs48/AreaShop#249] opened 2016-11-20 14:27 UTC
https://github.com/NLthijs48/AreaShop/wiki/The-config-system

I have a working groups.yml, we setup a server city on a test server and moved it to the live server, the shops disnt re-pickup the maxRentTime from the groups the shops were assigned to and so they defaulted to default.yml settings even though in-game they were even listed as in the right group, I thought my syntax must be wrong or something, but after removing the shop and recreating it it set the right maxRentTime in the groups.yml. There isnt any other way to edit already rented shops, and update them, I cant just do /as reload and it updates the group shops. I cant edit them manually in the region files, the only way I can tell the shops to actually listen to the setting maxRentTime in the group.yml is to re-create the shop, which is a massive pain if they shops already rented, and you have 76 of them.

**Comment by NLthijs48** [comment] 2016-11-20 14:36
Show me your groups.yml, default.yml and config.yml please, then I can tell you if the syntax is correct or not.

**Comment by FrozenBeard** [comment] 2016-11-20 16:19
This isn't "support", its not a syntax issue its a bug, I have tested it.
As I said in the intitial post, my groups **WORK**, they would not work if the syntax was broken, thje issue is listed above this isnt a support/syntax issue @NLthijs48 .

But I will show them anyway just so we can progress on this bug.
config.yml http://pastebin.com/eG6EN5rL
default.yml http://pastebin.com/huWgyGn8
groups.yml http://pastebin.com/1qLyy6fh

**Comment by NLthijs48** [comment] 2016-11-20 19:44
I'm sorry that I irritated you by labeling this Support, but with your initial message I'm not able to test or confirm anything about this, so therefore I had no reason to believe it is a bug yet. The new issue template is there for a reason and tell your to attach config files and list version numbers (which I still need), because that is what I need to reproduce and investigate a problem. I hope that just like me you want to solve the issue instead of arguing about labels, so let see what we can do.

I loaded your config files on my test server and added one of my regions to the docks group. When I was OP I could bypass the limits you have set in the groups.yml file, which is because of the permissions assigned to OP. But when I removed OP I first was rejected because I could not extend it anymore (`maxExtends` is set to `0`) and when I removed the maxExtends limit the limit of maxRentTime was in effect.

So check if you are OP or have `areashop.*`, because that will cause you to bypass the limit.

**Comment by FrozenBeard** [comment] 2016-11-22 15:38
Version number:  2.3.2
Spigot Version (1.10.2) Paper version git-Paper-916 (MC: 1.10.2) (Implementing API version   1.10.2-R0.1-SNAPSHOT)

This is not as silly as "I was OP", please do read the initial ticket describing the issue, I will try and re-explain. Im talking specifically about updating existing shops that players (PLayers are NOT OP) maxRentTime on their shops, If I create a NEW shop then the values are set correctly, whats NOT happening is even though the shops are in teh correct group, and listed as so in game, they maxRentTime is NOT being updated for existing shops players have rented, the only way to get around this is to destroy their shop and re-create it, which brings in a ton of its own issues.

**Comment by NLthijs48** [comment] 2016-11-25 15:52
It looks like you can better send me a zip archive containing your complete `/plugins/AreaShop` folder because I still do not exactly get how this problem is happening.

Being OP is a common mistake, so therefore I mentioned it, I still can only guess solutions and not exactly give you one that works because I cannot reproduce the issue.

Some questions and notes:
- How do you determine that the maxRentTime value is not set correctly on the shop? (checking the output of `/as info region <region>`? Trying to rent the region more than the maximum?)
- Note that the maxRentTime is never actually set on a region, each time AreaShop needs the value it will first look into the region file itself, then in the assigned groups, and then in default.yml. So a difference between new and existing shops cannot exist if the mentioned config files are setup the same.
- Do you expect a rented region to actually become rented less if you set the maxRentTime to something lower than it was before? Because that is not a thing, it should prevent the player from extending it until it is below the maxRentTime though.

**Comment by FrozenBeard** [comment] 2016-11-29 13:45
1. maxRentTime was determined by the output of /as info region <region>
2. The maxRentTime isn't set on the region, that is the issue; It only checks the groups when the shop is first created, you cannot update a shop that has already been created. or by running /as schemevent <region> created, this is again not a good solution, as this then creates a schematic based from the shop thats been modified, so all the modified claim blocks are then added. This is another issue within itself, as you cannot expand a shop size without re-creating the entire shop from scatch, you cannot update an already rented shop. 

What I suggest is you add another event option, an UPDATE to update existing rented shops, it could be added to the /as schemevent command.

/as schemevent <region> <created, deleted, rented, unrented, bought, sold, **update**>

so then we could have a way to update the size of shops, for areashop to then re-check the groups file to check for the maxRentTime, this would fix 2 bugs at once.

**Comment by NLthijs48** [comment] 2016-12-04 22:21
> It only checks the groups when the shop is first created,

I already explained that this is not the case, it checks it every time it wants to know something about a region.

> you cannot update a shop that has already been created

You should never have to, if you change something ingame it will update automatically, and if you change something in the config you need to use `/as reload` to reload the config, which also updates the signs and WorldGuard flags of all regions. `/as schemevent` is only to trigger the schematic operations as defined in the `config.yml` file in the `schematicProfiles` section, not to update the region in any other way.

> you cannot expand a shop size without re-creating the entire shop from scatch, you cannot update an already rented shop

For changing the region size I created a [feature ticket](https://github.com/NLthijs48/AreaShop/issues/259), it is quite involved though and not ready for implementation yet.

> It looks like you can better send me a zip archive containing your complete /plugins/AreaShop folder because I still do not exactly get how this problem is happening.

This still applies, we have still not moved forward anything.

**Comment by NLthijs48** [comment] 2017-02-15 21:03
I'm assuming your problem has been solved.

**Closed by NLthijs48** 2017-02-15 21:03 UTC
Labels: Support
