### ISSUE TITLE
Pls Help Me With This Problem

### ISSUE THREAD

**Issue by ProfileDK** [NLthijs48/AreaShop#342] opened 2017-08-02 20:26 UTC
Every Time I'm trying to download the plugin it says Error downloading plugin AreaShop.jar: HTTP Error 503: Service Temporarily Unavailable 
Pls Help

**Comment by NLthijs48** [comment] 2017-08-02 20:28
You can download it from [Spigot](https://www.spigotmc.org/resources/areashop.2991/), [Bukkit](https://dev.bukkit.org/projects/regionbuyandrent), [Github ](https://github.com/NLthijs48/AreaShop/releases)or a development build from [Jenkins](http://wiefferink.me:8080/job/AreaShop/).

At least one should work :D

**Comment by ProfileDK** [comment] 2017-08-02 20:37
Thanks, Im Gonna Try

**Comment by ProfileDK** [comment] 2017-08-02 20:39
Does The Plugin work with spigot 1.8.8?
Just Asking

**Comment by NLthijs48** [comment] 2017-08-02 20:41
Yes it should, that is the lowest version that still works with the latest AreaShop

**Comment by ProfileDK** [comment] 2017-08-02 20:43
When I'm Downloading it on NiceHosting thats were I have my server and that says
Download failed: Error downloading plugin AreaShop.jar: HTTP Error 503: Service Temporarily Unavailable

**Comment by ProfileDK** [comment] 2017-08-02 20:43
can i fix that some how?

**Comment by ProfileDK** [comment] 2017-08-02 20:46
and i tried on github now and spigot and jenkins
and it dont work

**Comment by NLthijs48** [comment] 2017-08-02 21:01
How are you downloading it? What does it have to do with your hosting provider?

You can just download it to your computer and upload it with FTP or something like that right?

**Comment by ProfileDK** [comment] 2017-08-02 21:03
what do you mean with FTP the mod?

**Comment by ProfileDK** [comment] 2017-08-02 21:03
but im gonna try what ever you are talking about

**Comment by ProfileDK** [comment] 2017-08-02 21:04
oh you mean FTP-File

**Comment by ProfileDK** [comment] 2017-08-02 21:04
Sorry

**Comment by ProfileDK** [comment] 2017-08-02 21:05
øhhhhh i still cant

**Comment by NLthijs48** [comment] 2017-08-02 21:07
FTP is not a file, it is a protocol to connect to a server to transfer files. Are you trying to download AreaShop  using some panel from your hosting provider?

**Comment by ProfileDK** [comment] 2017-08-02 21:16
No

**Comment by NLthijs48** [comment] 2017-08-02 21:17
Where and how do you see the `Download failed: Error downloading plugin AreaShop.jar: HTTP Error 503: Service Temporarily Unavailable` message?

**Comment by ProfileDK** [comment] 2017-08-02 21:17
on the console

**Comment by NLthijs48** [comment] 2017-08-02 21:18
Why does the console try to download AreaShop.jar and from where?

**Comment by ProfileDK** [comment] 2017-08-02 21:18
it doesnt the console can just see if the download failed and i can command on the console

**Comment by NLthijs48** [comment] 2017-08-02 21:19
Are you trying to install AreaShop by using some kind of command? I still have no idea how you are trying to download/install the plugin.

**Comment by ProfileDK** [comment] 2017-08-02 21:20
No Im Trying to download with the download on the website nicehosting and the links you send me

**Comment by NLthijs48** [comment] 2017-08-02 21:23
It looks like your host has some issues, but I can't tell, can you show what you are doing with screenshots or something?

**Comment by ProfileDK** [comment] 2017-08-02 21:25
it will be a little hard because I have a danish google chrome because I'm from Denmark

**Comment by ProfileDK** [comment] 2017-08-02 21:32
but here is a little screenshot 
![screenshot_1](https://user-images.githubusercontent.com/30669732/28895993-e55d68f0-77da-11e7-8b7f-a0abdf7212ee.png)

**Comment by NLthijs48** [comment] 2017-08-02 21:40
And when uploading the file you get that error message?

It looks like you need to contact your host and ask them why FTP does not work. You can try uploading another file to see if the problem is at your host.

**Comment by ProfileDK** [comment] 2017-08-02 21:41
Ok im gonna try

**Comment by ProfileDK** [comment] 2017-08-02 21:44
it doesnt work im gonna conatct the owner of the website

**Comment by NLthijs48** [comment] 2017-10-16 14:50
I assume your problem is solved, closing the issue

**Closed by NLthijs48** 2017-10-16 14:50 UTC
Labels: Support
