### ISSUE TITLE
Bad translation on French

### ISSUE THREAD

**Issue by jewome62** [NLthijs48/AreaShop#268] opened 2016-12-25 02:45 UTC
#### Current behavior
![image](https://cloud.githubusercontent.com/assets/472429/21469519/090fb2f6-ca54-11e6-9aef-4c90559b6f19.png)

And i don't understand, the translation look like good
![image](https://cloud.githubusercontent.com/assets/472429/21469521/844ba362-ca54-11e6-8db9-23241d4f18af.png)

#### Steps to reproduce (for bugs)
1. test a command with region parameter

#### Your environment (for bugs)

 * Server platform Spigot
 * Server version: 1.11.0
 * AreaShop version: Build 109 on Jenkins
 * WorldEdit version: 6.1.5
 * WorldGuard version: 6.1.3 SNAPSHOT
 * Vault version: 1.5.6

#### Your config files (for bugs)

https://jewome62.eu/owncloud/s/b5hS9rLhXFHUvJe

**Comment by NLthijs48** [comment] 2016-12-25 20:51
There was one broken translation, which was already reported by another user so I fixed that. I did not pull the translations from Transifex into the development version of AreaShop yet, so those are not updated.

You could copy the French translation for now and edit the message yourself (the problem is that there is a line above the e in `%lang:tRegion`). I'm closing this issue because it has been fixed already, you can still comment though.

**Closed by NLthijs48** 2016-12-25 20:51 UTC
